<fieldset ng-class="creare-info">
	<table>
		<tr>
		<td><img src="//www.antonioloiaconodesign.it/img/calculate-discount.gif" alt="Calculate Discount" /></td>
			<td width="10"></td><td>
			<h3>Calculate Discount version <?php echo $this->getModuleVersion() ?></h3>
				<p><strong><a href="<?php echo $this->getCalculateDiscountInfo() ?>" target="_blank">Info & Details</a></strong> - Calculate Discount - How to use
				<br /><strong><a href="<?php echo $this->getAldWebsite() ?>" target="_blank">ALD</a></strong> - for more about Antonio Loiacono Design
			</td>
		</tr>
	</table>
</fieldset>